name: Input and Output

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  input-output:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Output
        run: |
          echo "Hello, world!"
          echo {1..10}
          echo {a..k}